### PR TITLE
Auth tests

### PR DESCRIPTION
**Pull request by ARtoriouSs**

### CODE REVIEW

**Comment by mirterious** [comment]
@ARtoriouSs Do we still need this changes?

**Comment by ARtoriouSs** [comment]
> @ARtoriouSs Do we still need this changes?

Of course, this is WIP, I'll finish it **someday** :)

**Comment by mirterious** [comment]
> > @ARtoriouSs Do we still need this changes?
> 
> Of course, this is WIP, I'll finish it **someday** :)

Fuck, I thought it was rollback to ExUnit :)

**Comment by ARtoriouSs** [comment]
Closing this in favor of #68

**Pull request closed without merging**
